version: '3.1'

services:
  
  db:
    image: webdizz/oracle-xe-11g-sa:latest
    environment:
      - DATABASES=meudb
    ports:
      - 15080:8080
      - 1521:1521
    volumes:
      - meudb:/u01/app/oracle

volumes:
  meudb:
    external:
      name: meudb
    
    
      